//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Client.HotelService
{
    using System.ServiceModel;
    using Contracts;

    [ServiceContract]
    public interface IHotelService
    {
        [OperationContract]
        void BookHotel(BookingInfo info);
    }

    public class HotelServiceClient : ClientBase<IHotelService>, IHotelService
    {
        public HotelServiceClient(string endpointConfigName) : base(endpointConfigName) { }

        public void BookHotel(BookingInfo info)
        {
            base.Channel.BookHotel(info);
        }
    }
}
