//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Client.PaymentService
{
    using System.ServiceModel;
    using Contracts;

    [ServiceContract]
    public interface IPaymentService
    {
        [OperationContract]
        void MakePayment(BookingInfo info);
    }

    public class PaymentServiceClient : ClientBase<IPaymentService>, IPaymentService
    {
        public PaymentServiceClient(string endpointConfigName) : base(endpointConfigName) { }

        public void MakePayment(BookingInfo info)
        {
            base.Channel.MakePayment(info);
        }
    }
}
