//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Client.NotificationService
{
    using System.ServiceModel;
    using Contracts;

    [ServiceContract]
    public interface INotificationService
    {
        [OperationContract]
        void SendNotification(Notification notification);
    }

    public class NotificationServiceClient : ClientBase<INotificationService>, INotificationService
    {
        public NotificationServiceClient(string endpointConfigName) : base(endpointConfigName) { }

        public void SendNotification(Notification notification)
        {
            base.Channel.SendNotification(notification);
        }
    }
}
