//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Client.FlightService
{
    using System.ServiceModel;
    using Contracts;

    [ServiceContract]
    public interface IFlightService
    {
        [OperationContract]
        void BookFlight(BookingInfo info);
    }

    public class FlightServiceClient : ClientBase<IFlightService>, IFlightService
    {
        public FlightServiceClient(string endpointConfigName) : base(endpointConfigName) { }

        public void BookFlight(BookingInfo info)
        {
            base.Channel.BookFlight(info);
        }
    }
}
